name: kuma_flutter_app
description: 쿠마 앱 플러터

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_bloc: ^6.1.3
  url_launcher: ^6.0.3
  intl: ^0.16.1
  crypto: ^3.0.1
  vibration: ^1.7.3
  smooth_page_indicator: ^0.2.0
  flutter_simple_rating_bar: 0.0.3
  font_awesome_flutter: ^8.12.0
  youtube_player_flutter: ^8.0.0
  focus_detector: ^1.1.0+1
  toggle_switch: ^0.1.8
  path_provider: ^1.6.27
  fluttertoast: ^7.1.6
  platform: ^2.2.1
  package_info: ^0.4.0+18
  retrofit: ^1.3.4
  percent_indicator: ^3.0.1
  auto_size_text: ^2.1.0
  json_annotation: ^3.0.1
  kakao_flutter_sdk: ^0.5.4
  google_sign_in: ^4.5.9
  meta: ^1.1.8
  image_picker: ^0.6.7+14
  pretty_dio_logger: ^1.1.0
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_local_notifications: ^4.0.1
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0
  equatable: ^1.1.1
  dio: 3.0.10
  shared_preferences: 0.5.12+4
  rxdart: ^0.25.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  retrofit_generator: ^1.3.7
  json_serializable: ^3.2.0

flutter:
  assets:
    - assets/
    - assets/images/no_image.png
    - assets/images/google_icon.png
    - assets/images/google_logo.png
    - assets/images/kakao_talk_logo.png
    - assets/images/kakao_talk_logo_color.png
    - assets/images/email_icon.png
  fonts:
    - family: NanumPenScript
      fonts:
            - asset: assets/fonts/NanumPenScript-Regular.ttf
              weight: 400

    - family: DoHyeon
      fonts:
            - asset: assets/fonts/DoHyeon-Regular.ttf
              weight: 700

    - family: NanumGothic
      fonts:
            - asset: assets/fonts/NanumGothic-Regular.ttf

  uses-material-design: true

