name: kuma_flutter_app
description: 쿠마 앱 플러터

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  smooth_page_indicator: ^0.2.0
  flutter_rating_bar: ^3.2.0+1
  focus_detector: ^1.1.0+1
  path_provider: ^1.6.27
  fluttertoast: ^7.1.6
  retrofit: ^1.3.4
  percent_indicator: ^2.1.9+1
  auto_size_text: ^2.1.0
  logger: ^0.9.2  #for logging purpose
  json_annotation: ^3.0.1
  meta: ^1.1.8
  image_picker: ^0.6.7+14
  pretty_dio_logger: ^1.1.0
  equatable: ^1.1.1
  dio: 3.0.10
  uuid: 2.2.2
  flutter_bloc: ^6.0.1
  shared_preferences: 0.5.12+4
  circular_check_box: ^1.0.4
  rxdart: ^0.25.0
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  retrofit_generator: ^1.3.7
  json_serializable: ^3.2.0

flutter:
  assets:
    - assets/
  fonts:
    - family: NanumGothic
      fonts:
          - asset: assets/fonts/NanumGothic-Bold.ttf
          - asset: assets/fonts/NanumGothic-ExtraBold.ttf
            weight: 700

    - family: NanumPenScript
      fonts:
            - asset: assets/fonts/NanumPenScript-Regular.ttf
              weight: 400

  uses-material-design: true

